[package]
name = "spreadsheet"
version = "0.1.0"
authors = ["Zane Sterling <sterling.zane@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
